[package]
name = "anime_streamer"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-files = "0.6"
tera = "1.19"
tokio = { version = "1", features = ["full"] }
mime_guess = "2.0"
